env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  -
    binary: ksc
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  -
    builds:
      - ksc
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

nfpms:
  -
    vendor: ksc
    homepage:  https://github.com/chenz24/ks-cli
    maintainer: "ChenZhen chenz8606@gmail.com"
    description: "A command line interface for KubeSphere plugin system"
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/local/bin

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^assets:"
      - "^scripts:"
