
# Anything that does not need to be filled in by the user can be deleted, and the value of value.yaml in the charts directory will be overwritten
base:
  # The name and port of the SVC configured as the dashboard
  extSvcName: demo
  extSvcPort: 80
  # Mount location e.g. topbar,global,toolbox,access,cluster,workspace,project,platformSettings
  extParent: topbar
  # The hyperlink name of the dashboard
  extTitle: demo
  # Open with iframe for embedding and link for new tab opening e.g. iframe,link
  extEmbed: iframe
