---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.extSvcName }}
  namespace: extension-[[ .Name ]]
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.global.extension.ingress.ingressClassName }}
  rules:
    - host: "[[ .Name ]].{{ .Values.global.extension.ingress.domainSuffix }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.extSvcName }}
                port:
                  number: {{ .Values.extSvcPort }}